### PR TITLE
Pretty printing of exception messages

### LINKED ISSUE #78: Semantic highlighting for exception messages
Spectre.Console has a feature where it parses and highlights different parts of exception messages.

See [here](https://twitter.com/firstdrafthell/status/1312139828960530432?s=20):

image

It looks cool! We should steal it!

### PR DESCRIPTION
**Pull request by 89netraM**
This PR adds functionality that parse, formats, and highlights any exception that is thrown.

Error messages can also be shortened with the use of `UseShortErrors` when building the `CliApplication`. This option is stored in the `ApplicationConfiguration`.

The printout of two error messages. First is without the `UseShortErrors` option, and the second is with. Otherwise they're the same.  
Screenshot of errors without and with short errors

I've added a test that checks that printed error messages do not contain any fully qualified names when the `UseShortErrors` option is activated. And I also change the existing test of error printing to check that the fully qualified names are there.

Should close #78

### CODE REVIEW

File: CliFx/Domain/ErrorTextWriter.cs [hunk 1]
```diff
@@ -0,0 +1,138 @@
...
+        private static readonly ConsoleColor SpecificNameColor = ConsoleColor.White;
+        private static readonly ConsoleColor MessageColor = ConsoleColor.Red;
+        private static readonly ConsoleColor MethodColor = ConsoleColor.Yellow;
+        private static readonly ConsoleColor ParameterTypeColor = ConsoleColor.Blue;
+        private static readonly ConsoleColor FileColor = ConsoleColor.Yellow;
+        private static readonly ConsoleColor LineColor = ConsoleColor.Blue;
+
+        private static readonly Lazy<Regex> MethodMatcher = new Lazy<Regex>(() => new Regex(@"(?<prefix>\S+) (?<name>.*?)(?<methodName>[^\.]+)\("));
+        private static readonly Lazy<Regex> ParameterMatcher = new Lazy<Regex>(() => new Regex(@"(?<type>.+? )(?<name>.+?)(?:(?<separator>, )|\))"));
+        private static readonly Lazy<Regex> FileMatcher = new Lazy<Regex>(() => new Regex(@"(?<prefix>\S+?) (?<path>.*?)(?<file>[^\\/]+?(?:\.\w*)?):[^:]+? (?<line>\d+)"));
```
Comment (Tyrrrz) [inline CliFx/Domain/ErrorTextWriter.cs:20]: Regex are already pretty much lazy unless you compile them, so there's no reason in doing this.

File: CliFx/Domain/ErrorTextWriter.cs [hunk 2]
```diff
@@ -0,0 +1,138 @@
...
+        {
+            _configuration = configuration;
+            _console = console;
+        }
+
+        public void WriteError(Exception ex) => WriteError(ex, 0);
+        private void WriteError(Exception ex, int indentLevel)
+        {
+            var indentation = new String(' ', indent * indentLevel);
+            var extraIndentation = new String(' ', indent / 2);
```
Comment (Tyrrrz) [inline CliFx/Domain/ErrorTextWriter.cs:35]: Please use lowercase `string`

**Comment by Tyrrrz** [comment]
Thanks for the PR!

I think we should drop `UseShortErrors`, I highly doubt anyone is going to configure this as in pretty much every case you want as detailed error messages as possible.

**Comment by 89netraM** [comment]
Great! I'll get straight to your comments.

**Comment by Tyrrrz** [comment]
Thanks! One thing to consider: on the off chance that parsing fails, can we guarantee that the unformatted error message will be shown anyway?

**Comment by 89netraM** [comment]
Good point. No, probably not.

The exception type and message isn't parsed and can't fail so there's no need to check them.  
But as for the stack trace, unless the format of the stack trace is change I'm *pretty* sure it can't fail, but that's no guarantee. I can add a check that if any parsing fails the original stack trace will be printed instead.

What do you think?

**Comment by Tyrrrz** [comment]
Maybe we should try to parse the full stacktrace in one go instead of going by each line separately. So that way if any of the matches fail, we can just fallback to unformatted version easily.

**Comment by 89netraM** [comment]
Yes, exactly!  
I'll get right on it.

**Comment by Tyrrrz** [comment]
Looks good! Thanks!
